ddp:
  ddp_enable: False
  world_size: 1
  gpus: [0]
  
model:  
  num_layers: 18
  weights_init: True

  #ablation - choose between fusion model(fusion) and baseline model(fsm)
  depth_model: 'fsm'
  pose_model: 'fsm'

data:
  data_path: './input_data/nuscenes/'
  log_dir: './results/'
  dataset: 'nuscenes'
  back_context: 1
  forward_context: 1
  depth_type: 'lidar'
  cameras: ['CAM_FRONT', 'CAM_FRONT_LEFT', 'CAM_FRONT_RIGHT', 'CAM_BACK_LEFT', 'CAM_BACK_RIGHT', 'CAM_BACK']
  train_requirements: (gt_pose, mask)
  val_requirements: (gt_pose, gt_depth, mask)

training:
  # Basic
  height: 352
  width: 640
  scales: [0] 
  frame_ids: [0, -1, 1]
  
  # optimization
  batch_size: 2
  num_workers: 2
  learning_rate: 0.0001
  num_epochs: 4
  scheduler_step_size: 15
  
  # Depth synthesis
  aug_depth: False
  syn_visualize: False

  # model / loss setting
  ## Depth range
  min_depth: 1.5
  max_depth: 80.0

  ## Spatio & temporal
  spatio: True
  spatio_temporal: True

  ## Intensity align
  intensity_align: True
  
  ## Focal length scaling
  focal_length_scale: 300

# Loss hyperparams
loss:
  disparity_smoothness: 0.1 # For convergence
  spatio_coeff: 0.03
  spatio_tempo_coeff: 0.1
  pose_loss_coeff: 0.1
  
eval:
  eval_batch_size: 4
  eval_num_workers: 4
  eval_min_depth: 0
  eval_max_depth: 80
  eval_visualize: False
  syn_visualize: False
  syn_idx: None

load:
  pretrain: False
  weights: 'weights_3'
  models_to_load: ['depth_net']
  
logging:
  early_phase: 2000
  log_frequency: 100
  late_log_frequency: 1000
  save_frequency: 1
